/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.ProductOffering;
import io.swagger.model.ProductOfferingCreate;
import io.swagger.model.ProductOfferingUpdate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-09-28T13:08:23.907Z")

@Validated
@Api(value = "productOffering", description = "the productOffering API")
@RequestMapping(value = "/tmf-api/productCatalogManagement/v4/")
public interface ProductOfferingApi {

    @ApiOperation(value = "Creates a ProductOffering", nickname = "createProductOffering", notes = "This operation creates a ProductOffering entity.", response = ProductOffering.class, tags={ "productOffering", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = ProductOffering.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error.class),
        @ApiResponse(code = 405, message = "Method Not allowed", response = Error.class),
        @ApiResponse(code = 409, message = "Conflict", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/productOffering",
        produces = { "application/json;charset=utf-8" }, 
        consumes = { "application/json;charset=utf-8" },
        method = RequestMethod.POST)
    ResponseEntity<ProductOffering> createProductOffering(@ApiParam(value = "The ProductOffering to be created" ,required=true )  @Valid @RequestBody ProductOfferingCreate productOffering);


    @ApiOperation(value = "Deletes a ProductOffering", nickname = "deleteProductOffering", notes = "This operation deletes a ProductOffering entity.", tags={ "productOffering", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error.class),
        @ApiResponse(code = 404, message = "Not Found", response = Error.class),
        @ApiResponse(code = 405, message = "Method Not allowed", response = Error.class),
        @ApiResponse(code = 409, message = "Conflict", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/productOffering/{id}",
        produces = { "application/json;charset=utf-8" }, 
        consumes = { "application/json;charset=utf-8" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteProductOffering(@ApiParam(value = "Identifier of the ProductOffering",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "List or find ProductOffering objects", nickname = "listProductOffering", notes = "This operation list or find ProductOffering entities", response = ProductOffering.class, responseContainer = "List", tags={ "productOffering", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = ProductOffering.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error.class),
        @ApiResponse(code = 404, message = "Not Found", response = Error.class),
        @ApiResponse(code = 405, message = "Method Not allowed", response = Error.class),
        @ApiResponse(code = 409, message = "Conflict", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/productOffering",
        produces = { "application/json;charset=utf-8" }, 
        consumes = { "application/json;charset=utf-8" },
        method = RequestMethod.GET)
    ResponseEntity<List<ProductOffering>> listProductOffering(@ApiParam(value = "Comma-separated properties to be provided in response") @Valid @RequestParam(value = "fields", required = false) String fields,@ApiParam(value = "Requested index for start of resources to be provided in response") @Valid @RequestParam(value = "offset", required = false) Integer offset,@ApiParam(value = "Requested number of resources to be provided in response") @Valid @RequestParam(value = "limit", required = false) Integer limit);


    @ApiOperation(value = "Updates partially a ProductOffering", nickname = "patchProductOffering", notes = "This operation updates partially a ProductOffering entity.", response = ProductOffering.class, tags={ "productOffering", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated", response = ProductOffering.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error.class),
        @ApiResponse(code = 404, message = "Not Found", response = Error.class),
        @ApiResponse(code = 405, message = "Method Not allowed", response = Error.class),
        @ApiResponse(code = 409, message = "Conflict", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/productOffering/{id}",
        produces = { "application/json;charset=utf-8" }, 
        consumes = { "application/json;charset=utf-8" },
        method = RequestMethod.PATCH)
    ResponseEntity<ProductOffering> patchProductOffering(@ApiParam(value = "Identifier of the ProductOffering",required=true) @PathVariable("id") String id,@ApiParam(value = "The ProductOffering to be updated" ,required=true )  @Valid @RequestBody ProductOfferingUpdate productOffering);


    @ApiOperation(value = "Retrieves a ProductOffering by ID", nickname = "retrieveProductOffering", notes = "This operation retrieves a ProductOffering entity. Attribute selection is enabled for all first level attributes.", response = ProductOffering.class, tags={ "productOffering", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = ProductOffering.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error.class),
        @ApiResponse(code = 404, message = "Not Found", response = Error.class),
        @ApiResponse(code = 405, message = "Method Not allowed", response = Error.class),
        @ApiResponse(code = 409, message = "Conflict", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/productOffering/{id}",
        produces = { "application/json;charset=utf-8" }, 
        consumes = { "application/json;charset=utf-8" },
        method = RequestMethod.GET)
    ResponseEntity<ProductOffering> retrieveProductOffering(@ApiParam(value = "Identifier of the ProductOffering",required=true) @PathVariable("id") String id,@ApiParam(value = "Comma-separated properties to provide in response") @Valid @RequestParam(value = "fields", required = false) String fields);

}
